name: Rust

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/robbiemckinstry/rust-tools:nightly
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Stable Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
            toolchain: stable
            components: rustfmt, clippy
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v1
        continue-on-error: true
      - name: Install Cargo Make
        uses: actions-rs/cargo@v1.0.1
        with:
          command: install
          args: cargo-make
      - name: Run Cargo Make
        uses: actions-rs/cargo@v1.0.1
        with:
          command: make
          args: ci-flow
